/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ammcp
 */
public class frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_Principal
     */
    public frm_Principal(String user) {
        initComponents();
        establecerUsuarioLabel(user);
          ReajsuteImagen("LogoBosquesSinFondo.png");
    }

    public void establecerUsuarioLabel(String usuario) {
        lblUsuario.setText(usuario);
    }
    
    public String obtenerUsarioLabel(){
        return lblUsuario.getText();
    }
    
    public void configurarBotonesSegunRol(String rol) {
        // Si el usuario es ADMIN, habilitar todos los botones
        if (rol.equals("ADMIN")) {
            habilitarTodosLosBotones();
        }
        // Si el usuario es SECRETARIO, habilitar los botones permitidos para este rol
        else if (rol.equals("SECRETARIO")) {
            habilitarBotonesSecretario();
        }
        // Si el usuario es PROFESOR, habilitar los botones permitidos para este rol
        else if (rol.equals("PROFESOR")) {
            habilitarBotonesProfesor();
        }
    }

    private void habilitarTodosLosBotones() {
        // Habilitar todos los botones
        btnSalir.setEnabled(true);
        btnPadres.setEnabled(true);
        btnGrados.setEnabled(true);
        btnMaterias.setEnabled(true);
        btnAlumnos.setEnabled(true);
        btnProfesores.setEnabled(true);
        btnAsistencias.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnReportes1.setEnabled(true);
        btnCalificaciones.setEnabled(true);
    }

    private void habilitarBotonesSecretario() {
        // Habilitar los botones permitidos para el rol de SECRETARIO
        btnSalir.setEnabled(true);
        btnPadres.setEnabled(true);
        btnGrados.setEnabled(true);
        btnMaterias.setEnabled(true);
        btnAlumnos.setEnabled(true);
        btnProfesores.setEnabled(true);
        btnAsistencias.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnReportes1.setEnabled(true);
        btnCalificaciones.setEnabled(false); // Deshabilitar el botón de Calificaciones
    }

    private void habilitarBotonesProfesor() {
        // Habilitar los botones permitidos para el rol de PROFESOR
        btnSalir.setEnabled(true);
        btnPadres.setEnabled(false);
        btnGrados.setEnabled(false);
        btnMaterias.setEnabled(false);
        btnAlumnos.setEnabled(false);
        btnProfesores.setEnabled(false);
        btnAsistencias.setEnabled(true); // Habilitar wl botón de Asistencias
        btnConsultas.setEnabled(false);
        btnReportes1.setEnabled(false);
        btnCalificaciones.setEnabled(true); // Habilitar el botón de Calificaciones
    }
    
    public void ReajsuteImagen(String nombreImagen)
    {
         ImageIcon imagen;
         Icon icono2;
    
           
           
        imagen = new ImageIcon("src/imagenes/"+nombreImagen);
        icono2 = new ImageIcon(imagen.getImage().getScaledInstance( jlbLogo.getWidth(), jlbLogo.getHeight(),Image.SCALE_DEFAULT));
        jlbLogo.setIcon(icono2); 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPadres = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        btnGrados = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jlbLogo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 250, 255));

        jPanel2.setBackground(new java.awt.Color(0, 130, 90));
        jPanel2.setLayout(null);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("               SALIR");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);
        btnSalir.setBounds(10, 330, 160, 50);

        btnMaterias.setBackground(new java.awt.Color(255, 255, 255));
        btnMaterias.setText("MATERIAS");
        btnMaterias.setBorder(null);
        btnMaterias.setBorderPainted(false);
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        jPanel2.add(btnMaterias);
        btnMaterias.setBounds(470, 170, 160, 50);

        btnProfesores.setBackground(new java.awt.Color(255, 255, 255));
        btnProfesores.setText("PROFESORES");
        btnProfesores.setBorder(null);
        btnProfesores.setBorderPainted(false);
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfesores);
        btnProfesores.setBounds(380, 260, 160, 50);

        btnAsistencias.setBackground(new java.awt.Color(255, 255, 255));
        btnAsistencias.setText("ASISTENCIAS");
        btnAsistencias.setBorder(null);
        btnAsistencias.setBorderPainted(false);
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });
        jPanel2.add(btnAsistencias);
        btnAsistencias.setBounds(10, 230, 160, 50);

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setText("USUARIOS'=");
        btnUsuarios.setBorder(null);
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios);
        btnUsuarios.setBounds(380, 330, 160, 50);

        btnPadres.setBackground(new java.awt.Color(255, 255, 255));
        btnPadres.setText("PADRES");
        btnPadres.setBorder(null);
        btnPadres.setBorderPainted(false);
        btnPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadresActionPerformed(evt);
            }
        });
        jPanel2.add(btnPadres);
        btnPadres.setBounds(280, 190, 160, 50);

        btnReportes1.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes1.setText("        REPORTES");
        btnReportes1.setBorder(null);
        btnReportes1.setBorderPainted(false);
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes1);
        btnReportes1.setBounds(10, 280, 160, 50);

        btnGrados.setBackground(new java.awt.Color(255, 255, 255));
        btnGrados.setText("GRADOS");
        btnGrados.setBorder(null);
        btnGrados.setBorderPainted(false);
        btnGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradosActionPerformed(evt);
            }
        });
        jPanel2.add(btnGrados);
        btnGrados.setBounds(380, 100, 160, 50);

        btnAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos.setText("ALUMNOS");
        btnAlumnos.setBorder(null);
        btnAlumnos.setBorderPainted(false);
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlumnos);
        btnAlumnos.setBounds(70, 80, 200, 60);

        btnCalificaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnCalificaciones.setText("CALIFICAIONES");
        btnCalificaciones.setBorder(null);
        btnCalificaciones.setBorderPainted(false);
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalificaciones);
        btnCalificaciones.setBounds(200, 330, 160, 50);

        btnConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas.setText("CONSULTAS");
        btnConsultas.setBorder(null);
        btnConsultas.setBorderPainted(false);
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultas);
        btnConsultas.setBounds(200, 260, 160, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 250, 255));
        jLabel3.setText("GESTIONES CENTRO EDUCATIVO JUCUTUMA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 10, 820, 58);

        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBosquesSinFondo.png"))); // NOI18N
        jPanel2.add(jlbLogo);
        jlbLogo.setBounds(670, 70, 260, 300);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 130, 90));
        jLabel5.setText("Usuario:");

        lblUsuario.setBackground(new java.awt.Color(0, 130, 90));
        lblUsuario.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 130, 90));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(754, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsistenciasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPadresActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGradosActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal("AMMC").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlumnos;
    public javax.swing.JButton btnAsistencias;
    public javax.swing.JButton btnCalificaciones;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnGrados;
    public javax.swing.JButton btnMaterias;
    public javax.swing.JButton btnPadres;
    public javax.swing.JButton btnProfesores;
    public javax.swing.JButton btnReportes1;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel jlbLogo;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
