/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ammcp
 */
public class frm_Principal extends javax.swing.JFrame {

    /**
     * Creates new form frm_Principal
     */
    public frm_Principal(String user) {
        initComponents();
        establecerUsuarioLabel(user);
          ReajsuteImagen("LogoBosquesSinFondo.png");
    }

    public void establecerUsuarioLabel(String usuario) {
        lblUsuario.setText(usuario);
    }
    
    public String obtenerUsarioLabel(){
        return lblUsuario.getText();
    }
    
    public void configurarBotonesSegunRol(String rol) {
        // Si el usuario es ADMIN, habilitar todos los botones
        if (rol.equals("ADMIN")) {
            habilitarTodosLosBotones();
        }
        // Si el usuario es SECRETARIO, habilitar los botones permitidos para este rol
        else if (rol.equals("SECRETARIO")) {
            habilitarBotonesSecretario();
        }
        // Si el usuario es PROFESOR, habilitar los botones permitidos para este rol
        else if (rol.equals("PROFESOR")) {
            habilitarBotonesProfesor();
        }
    }

    private void habilitarTodosLosBotones() {
        // Habilitar todos los botones
        btnSalir.setEnabled(true);
        btnPadres.setEnabled(true);
        btnGrados.setEnabled(true);
        btnMaterias.setEnabled(true);
        btnAlumnos.setEnabled(true);
        btnProfesores.setEnabled(true);
        btnAsistencias.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnReportes1.setEnabled(true);
        btnCalificaciones.setEnabled(true);
    }

    private void habilitarBotonesSecretario() {
        // Habilitar los botones permitidos para el rol de SECRETARIO
        btnSalir.setEnabled(true);
        btnPadres.setEnabled(true);
        btnGrados.setEnabled(true);
        btnMaterias.setEnabled(true);
        btnAlumnos.setEnabled(true);
        btnProfesores.setEnabled(true);
        btnAsistencias.setEnabled(true);
        btnConsultas.setEnabled(true);
        btnReportes1.setEnabled(true);
        btnCalificaciones.setEnabled(false); // Deshabilitar el botón de Calificaciones
    }

    private void habilitarBotonesProfesor() {
        // Habilitar los botones permitidos para el rol de PROFESOR
        btnSalir.setEnabled(true);
        btnPadres.setEnabled(false);
        btnGrados.setEnabled(false);
        btnMaterias.setEnabled(false);
        btnAlumnos.setEnabled(false);
        btnProfesores.setEnabled(false);
        btnAsistencias.setEnabled(true); // Habilitar wl botón de Asistencias
        btnConsultas.setEnabled(false);
        btnReportes1.setEnabled(false);
        btnCalificaciones.setEnabled(true); // Habilitar el botón de Calificaciones
    }
    
    public void ReajsuteImagen(String nombreImagen)
    {
         ImageIcon imagen;
         Icon icono2;
    
           
           
        imagen = new ImageIcon("src/imagenes/"+nombreImagen);
        icono2 = new ImageIcon(imagen.getImage().getScaledInstance( jlbLogo.getWidth(), jlbLogo.getHeight(),Image.SCALE_DEFAULT));
        jlbLogo.setIcon(icono2); 
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMaterias = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnAsistencias = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnPadres = new javax.swing.JButton();
        btnReportes1 = new javax.swing.JButton();
        btnGrados = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jlbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIONES CENTRO EDUCATIVO JUCUTUMA");

        jPanel1.setBackground(new java.awt.Color(241, 250, 255));

        jPanel2.setBackground(new java.awt.Color(0, 130, 90));
        jPanel2.setLayout(null);

        btnMaterias.setBackground(new java.awt.Color(255, 255, 255));
        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMaterias.png"))); // NOI18N
        btnMaterias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnMaterias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMateriasOn.png"))); // NOI18N
        btnMaterias.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMateriasOn.png"))); // NOI18N
        btnMaterias.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMateriasOn.png"))); // NOI18N
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });
        jPanel2.add(btnMaterias);
        btnMaterias.setBounds(200, 170, 140, 45);

        btnProfesores.setBackground(new java.awt.Color(255, 255, 255));
        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesores.png"))); // NOI18N
        btnProfesores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnProfesores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesoresOn.png"))); // NOI18N
        btnProfesores.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesoresOn.png"))); // NOI18N
        btnProfesores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesoresOn.png"))); // NOI18N
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });
        jPanel2.add(btnProfesores);
        btnProfesores.setBounds(20, 170, 140, 45);

        btnAsistencias.setBackground(new java.awt.Color(255, 255, 255));
        btnAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAsistencias.png"))); // NOI18N
        btnAsistencias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnAsistencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAsistenciasOn.png"))); // NOI18N
        btnAsistencias.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAsistenciasOn.png"))); // NOI18N
        btnAsistencias.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAsistenciasOn.png"))); // NOI18N
        btnAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenciasActionPerformed(evt);
            }
        });
        jPanel2.add(btnAsistencias);
        btnAsistencias.setBounds(370, 100, 140, 45);

        btnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnUsuarios.png"))); // NOI18N
        btnUsuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnUsuarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnUsuariosOn.png"))); // NOI18N
        btnUsuarios.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnUsuariosOn.png"))); // NOI18N
        btnUsuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnUsuariosOn.png"))); // NOI18N
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel2.add(btnUsuarios);
        btnUsuarios.setBounds(200, 240, 140, 45);

        btnPadres.setBackground(new java.awt.Color(255, 255, 255));
        btnPadres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadres.png"))); // NOI18N
        btnPadres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnPadres.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadresOn.png"))); // NOI18N
        btnPadres.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadresOn.png"))); // NOI18N
        btnPadres.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadresOn.png"))); // NOI18N
        btnPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadresActionPerformed(evt);
            }
        });
        jPanel2.add(btnPadres);
        btnPadres.setBounds(370, 240, 140, 45);

        btnReportes1.setBackground(new java.awt.Color(255, 255, 255));
        btnReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnReportes.png"))); // NOI18N
        btnReportes1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnReportes1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnReportesOn.png"))); // NOI18N
        btnReportes1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnReportesOn.png"))); // NOI18N
        btnReportes1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnReportesOn.png"))); // NOI18N
        btnReportes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportes1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnReportes1);
        btnReportes1.setBounds(200, 310, 140, 45);

        btnGrados.setBackground(new java.awt.Color(255, 255, 255));
        btnGrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGrados.png"))); // NOI18N
        btnGrados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnGrados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGradosOn.png"))); // NOI18N
        btnGrados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGradosOn.png"))); // NOI18N
        btnGrados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGradosOn.png"))); // NOI18N
        btnGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradosActionPerformed(evt);
            }
        });
        jPanel2.add(btnGrados);
        btnGrados.setBounds(200, 100, 140, 45);

        btnAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnos.png"))); // NOI18N
        btnAlumnos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnAlumnos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnosOn.png"))); // NOI18N
        btnAlumnos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnosOn.png"))); // NOI18N
        btnAlumnos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnosOn.png"))); // NOI18N
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlumnos);
        btnAlumnos.setBounds(20, 100, 140, 45);

        btnCalificaciones.setBackground(new java.awt.Color(255, 255, 255));
        btnCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificaciones.png"))); // NOI18N
        btnCalificaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnCalificaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificacionesOn.png"))); // NOI18N
        btnCalificaciones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificacionesOn.png"))); // NOI18N
        btnCalificaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificacionesOn.png"))); // NOI18N
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalificaciones);
        btnCalificaciones.setBounds(370, 170, 140, 45);

        btnConsultas.setBackground(new java.awt.Color(255, 255, 255));
        btnConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnConsultas.png"))); // NOI18N
        btnConsultas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 3, true));
        btnConsultas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnConsultasOn.png"))); // NOI18N
        btnConsultas.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnConsultasOn.png"))); // NOI18N
        btnConsultas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnConsultasOn.png"))); // NOI18N
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        jPanel2.add(btnConsultas);
        btnConsultas.setBounds(20, 240, 140, 45);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 250, 255));
        jLabel3.setText("GESTIONES CENTRO EDUCATIVO JUCUTUMA");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 540, 58);

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnSalir.png"))); // NOI18N
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 28, 36), 3, true));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnSalirOn.png"))); // NOI18N
        btnSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnSalirOn.png"))); // NOI18N
        btnSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnSalirOn.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir);
        btnSalir.setBounds(380, 310, 135, 45);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 130, 90));
        jLabel5.setText("BIENVENIDO:");

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(236, 28, 36));

        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBosquesSinFondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbLogo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsistenciasActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPadresActionPerformed

    private void btnReportes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportes1ActionPerformed

    private void btnGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGradosActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal("AMMC").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlumnos;
    public javax.swing.JButton btnAsistencias;
    public javax.swing.JButton btnCalificaciones;
    public javax.swing.JButton btnConsultas;
    public javax.swing.JButton btnGrados;
    public javax.swing.JButton btnMaterias;
    public javax.swing.JButton btnPadres;
    public javax.swing.JButton btnProfesores;
    public javax.swing.JButton btnReportes1;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel jlbLogo;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
