/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ammcp
 */
public class frm_Consulta extends javax.swing.JDialog {

    frm_Consulta_Alumnos formConsAlumnos = new frm_Consulta_Alumnos(this, true);
    frm_Consulta_Calificaciones formConsCalifs = new frm_Consulta_Calificaciones(this, true);
    frm_Consulta_Grados formConsGrados = new frm_Consulta_Grados(this, true);
    frm_Consulta_Materias formConsMaterias = new frm_Consulta_Materias(this, true);
    frm_Consulta_Padres formConsPadres = new frm_Consulta_Padres(this, true);
    frm_Consulta_Profesor formConsProfesor = new frm_Consulta_Profesor(this, true);
    frm_Consulta_Empleados formConsEmple = new frm_Consulta_Empleados(this,true);
    /**
     * Creates new form frm_Consulta_Producto
     */
    public frm_Consulta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        ReajsuteImagen("LogoBosquesSinFondo.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jlbLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGrados = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();
        btnMaterias = new javax.swing.JButton();
        btnPadres = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTAS");

        jPanel2.setBackground(new java.awt.Color(241, 250, 255));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 130, 90));
        jLabel3.setText("CONSULTAS");

        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LogoBosquesSinFondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jPanel1.setBackground(new java.awt.Color(0, 130, 90));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 2, true), "CONSULTAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(241, 250, 255))); // NOI18N

        btnGrados.setBackground(new java.awt.Color(0, 130, 90));
        btnGrados.setForeground(new java.awt.Color(0, 130, 90));
        btnGrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGrados.png"))); // NOI18N
        btnGrados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnGrados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGradosOn.png"))); // NOI18N
        btnGrados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGradosOn.png"))); // NOI18N
        btnGrados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnGradosOn.png"))); // NOI18N
        btnGrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradosActionPerformed(evt);
            }
        });

        btnAlumnos.setBackground(new java.awt.Color(0, 130, 90));
        btnAlumnos.setForeground(new java.awt.Color(0, 130, 90));
        btnAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnos.png"))); // NOI18N
        btnAlumnos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlumnos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnosOn.png"))); // NOI18N
        btnAlumnos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnosOn.png"))); // NOI18N
        btnAlumnos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnAlumnosOn.png"))); // NOI18N
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });

        btnCalificaciones.setBackground(new java.awt.Color(0, 130, 90));
        btnCalificaciones.setForeground(new java.awt.Color(0, 130, 90));
        btnCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificaciones.png"))); // NOI18N
        btnCalificaciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnCalificaciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificacionesOn.png"))); // NOI18N
        btnCalificaciones.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificacionesOn.png"))); // NOI18N
        btnCalificaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnCalificacionesOn.png"))); // NOI18N
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });

        btnMaterias.setBackground(new java.awt.Color(0, 130, 90));
        btnMaterias.setForeground(new java.awt.Color(0, 130, 90));
        btnMaterias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMaterias.png"))); // NOI18N
        btnMaterias.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnMaterias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMateriasOn.png"))); // NOI18N
        btnMaterias.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMateriasOn.png"))); // NOI18N
        btnMaterias.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnMateriasOn.png"))); // NOI18N
        btnMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriasActionPerformed(evt);
            }
        });

        btnPadres.setBackground(new java.awt.Color(0, 130, 90));
        btnPadres.setForeground(new java.awt.Color(0, 130, 90));
        btnPadres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadres.png"))); // NOI18N
        btnPadres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnPadres.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadresOn.png"))); // NOI18N
        btnPadres.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadresOn.png"))); // NOI18N
        btnPadres.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnPadresOn.png"))); // NOI18N
        btnPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadresActionPerformed(evt);
            }
        });

        btnProfesores.setBackground(new java.awt.Color(0, 130, 90));
        btnProfesores.setForeground(new java.awt.Color(0, 130, 90));
        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesores.png"))); // NOI18N
        btnProfesores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnProfesores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesoresOn.png"))); // NOI18N
        btnProfesores.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesoresOn.png"))); // NOI18N
        btnProfesores.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnProfesoresOn.png"))); // NOI18N
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });

        btnEmpleados.setBackground(new java.awt.Color(0, 130, 90));
        btnEmpleados.setForeground(new java.awt.Color(0, 130, 90));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnEmpleados.png"))); // NOI18N
        btnEmpleados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 250, 255), 4, true));
        btnEmpleados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnEmpleadosOn.png"))); // NOI18N
        btnEmpleados.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnEmpleadosOn.png"))); // NOI18N
        btnEmpleados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BtnEmpleadosOn.png"))); // NOI18N
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGrados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradosActionPerformed
        // TODO add your handling code here:
        formConsGrados.setVisible(true);
    }//GEN-LAST:event_btnGradosActionPerformed

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:
        formConsAlumnos.setVisible(true);
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        // TODO add your handling code here:
        formConsCalifs.setVisible(true);
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    private void btnMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriasActionPerformed
        // TODO add your handling code here:
        formConsMaterias.setVisible(true);
    }//GEN-LAST:event_btnMateriasActionPerformed

    private void btnPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadresActionPerformed
        // TODO add your handling code here:
        formConsPadres.setVisible(true);
    }//GEN-LAST:event_btnPadresActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        // TODO add your handling code here:
        formConsProfesor.setVisible(true);
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // TODO add your handling code here:
        formConsEmple.setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

      public void ReajsuteImagen(String nombreImagen)
    {
         ImageIcon imagen;
         Icon icono2;
    
           
           
        imagen = new ImageIcon("src/imagenes/"+nombreImagen);
        icono2 = new ImageIcon(imagen.getImage().getScaledInstance( jlbLogo.getWidth(), jlbLogo.getHeight(),Image.SCALE_DEFAULT));
        jlbLogo.setIcon(icono2); 
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Consulta dialog = new frm_Consulta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAlumnos;
    public javax.swing.JButton btnCalificaciones;
    public javax.swing.JButton btnEmpleados;
    public javax.swing.JButton btnGrados;
    public javax.swing.JButton btnMaterias;
    public javax.swing.JButton btnPadres;
    public javax.swing.JButton btnProfesores;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel jlbLogo;
    // End of variables declaration//GEN-END:variables
}
